version: "3.3"
services:
  service-A:
    build: .
    volumes:
      - /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
      - /var/run/docker.sock:/var/run/docker.sock


